-- SELECT top 1
-- T.Numero,
-- T.Nome,
-- S.Servico,
-- R.Recurso AS 'COLABORADOR',
-- CR.Gerente,
-- T.InicioReal,
-- T.TerminoReal,
-- T.Disponibilizacao,
-- ES.Descricao AS 'Local',
-- R.PerguntaDescricao AS 'Pergunta',
-- R.Conteudo AS 'Resposta',
-- E.Longitude_F,
-- E.Latitude_F,
-- ES.HIERARQUIADESCRICAO AS 'ESTRUTURA COMPLETA'
-- FROM DW_VISTA.DBO.FT_TAREFA T WITH(NOLOCK)
-- INNER JOIN DW_VISTA.DBO.FT_CHECKLIST_RESPOSTA_FULL R ON R.TarefaId = T.Id
-- INNER JOIN DW_VISTA.DBO.DM_EXECUCAO E ON E.TarefaId = T.Id
-- INNER JOIN DW_VISTA.DBO.DM_ESTRUTURA ES ON ES.Id_Estrutura = T.Id_Estrutura
-- INNER JOIN DW_VISTA.DBO.DM_CR CR ON CR.Id_CR = ES.Id_CR
-- inner JOIN DW_VISTA.DBO.DM_SERVICO S ON S.Id_Servico = T.Id_Servico
